Repository bulan-devs/gov-inventory-front-end, pull requests merged in 2021-04, with the labels that each got.

#27 Fixed invalid result on navigation
  src/components/Forms/Sidebar.vue
  src/pages/Login/Login.vue
Labels: invalid

#28 Change default icon into logo icon
  public/favicon.ico
  src/components/Forms/Navigation.vue
Labels: documentation, enhancement

#31 Logout/integration
  package.json
  src/assets/Icons.vue
  src/assets/loading.svg
  src/assets/svg/Search.svg
  src/assets/svg/profile.svg
  src/assets/svg2/Working.svg
  src/assets/svg_collection.js
  src/components/Accordion/Modules.vue
  src/components/Alert/DeleteAlert.vue
  src/components/Alert/ErrorAlert.vue
  src/components/Alert/SuccessAlert.vue
  src/components/Cards/UsersCards.vue
  src/components/Dropdown/MenuDot.vue
  src/components/Dropdown/ProfileMenu.vue
  src/components/Forms/LoginForm.vue
  src/components/Forms/Navigation.vue
  src/components/Forms/Sidebar.vue
  src/components/Input/Input.vue
  src/components/List/List.vue
  src/components/ListBelt/ListBelt.vue
  src/components/ListPagination/ListPagination.vue
  src/components/Loading/Searching.vue
  src/components/Modals/Modal.vue
  src/components/Stepper/Stepper.vue
  src/helpers/helpers.js
  src/helpers/uiHelpers.js
  src/index.css
  src/main.js
  src/pages/Dashboard/Dashboard.vue
  src/pages/Login/Login.vue
  src/pages/UserManagement/UserManagement.vue
  src/router/index.js
  src/store/actions/UserData/userDataActions.js
  src/store/actions/UserManagement/userManagementActions.js
  src/store/actions/actions.js
  src/store/mutations/UserManagement/UserManagementMutations.js
  src/store/mutations/mutations.js
  src/store/store.js
  tailwind.config.js
Labels: documentation, enhancement

#32 Logout/integration
  src/assets/svg_collection.js
  src/components/Accordion/Permission.vue
  src/components/Accordion/subPermission.vue
  src/components/Dropdown/ProfileMenu.vue
  src/components/List/List.vue
  src/store/actions/UserData/userDataActions.js
Labels: bug

#33 Changes in Parent Container for UserCards
  src/components/List/List.vue
Labels: enhancement

#39 Layout fixes
  src/components/Accordion/Accordion.vue
  src/components/List/List.vue
  src/components/List/PPMPList.vue
  src/pages/Dashboard/Dashboard.vue
  src/pages/Profile/Profile.vue
  src/pages/UserManagement/UserManagement.vue
  tailwind.config.js
Labels: documentation
